### ISSUE TITLE
"catch: TypeError: Cannot set property 'innerHTML' of undefined" appearing in Log

### ISSUE THREAD

**Issue by csylvain** [jks-prv/kiwiclient#80]
someone connecting from wildly different IP addresses but always tuning to 428.33 kHz upon arrival and causing a breadcrumb trail of
```
x-DEBUG 52.191.87.41 "audio_start.demodulator_analog_replace: catch: TypeError: Cannot set property 'innerHTML' of undefined"
```
entries in my kiwisdr log. 

is it possible this is evidence someone is probing for a vulnerability in the demodulation selection?

i have suspended all remote user access for the time being. should i continue to be cautious?

i would be reassured if something like this has happened in the past and has already been resolved with some confidence the avenue of illicit access has been closed.

**Comment by jks-prv** [comment]
First, why is this issue posted in the kiwiclient repo? Are these errors for certain coming from kiwiclient connections? (e.g. as indicated by the user/ident field on the Kiwi's list of client connections)

I added some try/catch statements in the Javascript a while back to attempt to report client-side errors to the server logs for analysis. But these just ended up interfering with other exception handlers that were already in place (like the audio_start one above). And I haven't gone back to sort out the problem yet.

So this is unlikely to be any malicious activity. It's just an HTML issue (undefined property for some reason). But if these are really kiwiclient connections then there should be no javascript involved. So that doesn't make any sense. Maybe this is one of the new third-party user interfaces? (e.g. Android app)

**Comment by jks-prv** [comment]
Okay, this turns out to be a side-effect of some code optimization that was made in the v1.425 release. I'll fix this in the next release and this error will no longer occur.

**Comment by csylvain** [comment]
okay, good news then. i keep a watchful eye on the Log in my kiwisdr (1.427 in use here). i was not certain i should "go public" (Forum) in case there was something not good going on. therefore i first wanted to communicate with you but without attracting very much attention.

what i could see in the log was a client arriving having last tuned 428.33 kHz, hence the immediate setting of the start freq, but in each case the client would not stick around very long and never from the same IP address twice. 

since this all was new messages being logged and a client poking at something causing the message to be emitted once or twice before leaving, i could not be certain what was going on was completely 'copasetic'. eah message was exactly the same with only the IP address corresponding to the client address shown when 428.33 and another freq was tuned.

**Comment by jks-prv** [comment]
There are a number of sites that do specialized sampling of Kiwis for things like SNR rankings. Because they might connect using the Kiwi API in manner that is slightly different than usual it may trigger bugs and that might be what we're seeing here. Although repeated short connections from differing ip addresses to the same frequency sounds a bit strange.

**Comment by UgoPoddine** [comment]
Hello,

still trying to perform statistical analysis of my FT8 spots to compare antenna performances, I'm curious regarding the sites you are referring to.
Can you share some detail ?

Thank-you 
IU1IPB Ugo

Il giorno 8 Dic 2020, 21:34, alle ore 21:34, John Seamons <notifications@github.com> ha scritto:

**Comment by jks-prv** [comment]
http://rx.linkfanel.net/snr.html
http://sibamanna.duckdns.org/sdr_map.html

We don't run either of these sites so cannot provide detail about how they work exactly.

**Comment by UgoPoddine** [comment]
Thank-you !!

Ugo

Il giorno 9 Dic 2020, 18:02, alle ore 18:02, John Seamons <notifications@github.com> ha scritto:
